n=int(input("Enter total number of people: "))
p=int(input("Enter the capacity of the people: "))
r=int(n/p)
print(r)
result=int(r+1)
print(result)
print("Elevator will be use ", int(result) ,"times.")
